export default {
  LOGO: require('./LOGO.jpeg'),
  LOGO2: require('./LOGO2.png'),
  OTP: require('./Otp.png'),
  PLUS: require('./plus.png'),
  POST1: require('./post1.jpg'),
  POST2: require('./post2.jpg'),
  POST3: require('./post3.jpg'),
  POST4: require('./post4.jpg'),
  USER: require('./userProfile.png'),
  AADHAAR: require('./aadhar.png'),
  COMMISSION: require('./setCommision.png'),
  CONNECT: require('./connect.png'),
  SEARCH: require('./search.png'),
  CONNECT_BG_REMOVE: require('./connectBgRemove.png'),
  // emoji
  SAD_EMOJI: require('./anguished.png'),
  HEART_EMOJI: require('./heart_eyes.png'),
  MONEY_EMOJI: require('./money_mouth_face.png'),
  YELLOW_EMOJI: require('./yellow_heart.png'),
  THUMB_EMOJI: require('./thumbDown.png'),
};
